//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Behaviortree
{
    [Serializable]
    public class ActiveMissionMsg : Message
    {
        public const string k_RosMessageName = "behaviortree_msgs/ActiveMission";
        public override string RosMessageName => k_RosMessageName;

        public sbyte mission;
        public const sbyte USER = 0;
        public const sbyte TARGET = 1;
        public const sbyte TARGET_BASE = 2;
        public const sbyte TARGET_EE = 3;
        public const sbyte GRASP = 4;
        public const sbyte DOOR_OPENING = 5;

        public ActiveMissionMsg()
        {
            this.mission = 0;
        }

        public ActiveMissionMsg(sbyte mission)
        {
            this.mission = mission;
        }

        public static ActiveMissionMsg Deserialize(MessageDeserializer deserializer) => new ActiveMissionMsg(deserializer);

        private ActiveMissionMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mission);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.mission);
        }

        public override string ToString()
        {
            return "ActiveMissionMsg: " +
            "\nmission: " + mission.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
