//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Behaviortree
{
    [Serializable]
    public class DoorOpeningMsg : Message
    {
        public const string k_RosMessageName = "behaviortree_msgs/DoorOpening";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public DoorInfoMsg door_info;
        public DoorOpeningModesMsg door_opening_mode;
        public Geometry.PoseStampedMsg base_start_pose;
        public Geometry.PoseStampedMsg base_grasp_pose;
        public Geometry.PoseStampedMsg base_end_pose;
        public Geometry.PoseStampedMsg base_intermediate_pose;
        public bool turn_handle;
        public bool push_pull;
        public bool default_pull;
        public bool validate_with_door_angle;
        public bool check_grasp;

        public DoorOpeningMsg()
        {
            this.header = new Std.HeaderMsg();
            this.door_info = new DoorInfoMsg();
            this.door_opening_mode = new DoorOpeningModesMsg();
            this.base_start_pose = new Geometry.PoseStampedMsg();
            this.base_grasp_pose = new Geometry.PoseStampedMsg();
            this.base_end_pose = new Geometry.PoseStampedMsg();
            this.base_intermediate_pose = new Geometry.PoseStampedMsg();
            this.turn_handle = false;
            this.push_pull = false;
            this.default_pull = false;
            this.validate_with_door_angle = false;
            this.check_grasp = false;
        }

        public DoorOpeningMsg(Std.HeaderMsg header, DoorInfoMsg door_info, DoorOpeningModesMsg door_opening_mode, Geometry.PoseStampedMsg base_start_pose, Geometry.PoseStampedMsg base_grasp_pose, Geometry.PoseStampedMsg base_end_pose, Geometry.PoseStampedMsg base_intermediate_pose, bool turn_handle, bool push_pull, bool default_pull, bool validate_with_door_angle, bool check_grasp)
        {
            this.header = header;
            this.door_info = door_info;
            this.door_opening_mode = door_opening_mode;
            this.base_start_pose = base_start_pose;
            this.base_grasp_pose = base_grasp_pose;
            this.base_end_pose = base_end_pose;
            this.base_intermediate_pose = base_intermediate_pose;
            this.turn_handle = turn_handle;
            this.push_pull = push_pull;
            this.default_pull = default_pull;
            this.validate_with_door_angle = validate_with_door_angle;
            this.check_grasp = check_grasp;
        }

        public static DoorOpeningMsg Deserialize(MessageDeserializer deserializer) => new DoorOpeningMsg(deserializer);

        private DoorOpeningMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            this.door_info = DoorInfoMsg.Deserialize(deserializer);
            this.door_opening_mode = DoorOpeningModesMsg.Deserialize(deserializer);
            this.base_start_pose = Geometry.PoseStampedMsg.Deserialize(deserializer);
            this.base_grasp_pose = Geometry.PoseStampedMsg.Deserialize(deserializer);
            this.base_end_pose = Geometry.PoseStampedMsg.Deserialize(deserializer);
            this.base_intermediate_pose = Geometry.PoseStampedMsg.Deserialize(deserializer);
            deserializer.Read(out this.turn_handle);
            deserializer.Read(out this.push_pull);
            deserializer.Read(out this.default_pull);
            deserializer.Read(out this.validate_with_door_angle);
            deserializer.Read(out this.check_grasp);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.door_info);
            serializer.Write(this.door_opening_mode);
            serializer.Write(this.base_start_pose);
            serializer.Write(this.base_grasp_pose);
            serializer.Write(this.base_end_pose);
            serializer.Write(this.base_intermediate_pose);
            serializer.Write(this.turn_handle);
            serializer.Write(this.push_pull);
            serializer.Write(this.default_pull);
            serializer.Write(this.validate_with_door_angle);
            serializer.Write(this.check_grasp);
        }

        public override string ToString()
        {
            return "DoorOpeningMsg: " +
            "\nheader: " + header.ToString() +
            "\ndoor_info: " + door_info.ToString() +
            "\ndoor_opening_mode: " + door_opening_mode.ToString() +
            "\nbase_start_pose: " + base_start_pose.ToString() +
            "\nbase_grasp_pose: " + base_grasp_pose.ToString() +
            "\nbase_end_pose: " + base_end_pose.ToString() +
            "\nbase_intermediate_pose: " + base_intermediate_pose.ToString() +
            "\nturn_handle: " + turn_handle.ToString() +
            "\npush_pull: " + push_pull.ToString() +
            "\ndefault_pull: " + default_pull.ToString() +
            "\nvalidate_with_door_angle: " + validate_with_door_angle.ToString() +
            "\ncheck_grasp: " + check_grasp.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
