//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Behaviortree
{
    [Serializable]
    public class DoorInfoMsg : Message
    {
        public const string k_RosMessageName = "behaviortree_msgs/DoorInfo";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public bool doorDetected;
        public float doorWidth;
        public float doorHeight;
        public int hingeSide;
        public bool doorType;
        public float handleGripWidth;
        public Geometry.PointMsg doorCenter;
        public Geometry.PoseStampedMsg handlePose;

        public DoorInfoMsg()
        {
            this.header = new HeaderMsg();
            this.doorDetected = false;
            this.doorWidth = 0.0f;
            this.doorHeight = 0.0f;
            this.hingeSide = 0;
            this.doorType = false;
            this.handleGripWidth = 0.0f;
            this.doorCenter = new Geometry.PointMsg();
            this.handlePose = new Geometry.PoseStampedMsg();
        }

        public DoorInfoMsg(HeaderMsg header, bool doorDetected, float doorWidth, float doorHeight, int hingeSide, bool doorType, float handleGripWidth, Geometry.PointMsg doorCenter, Geometry.PoseStampedMsg handlePose)
        {
            this.header = header;
            this.doorDetected = doorDetected;
            this.doorWidth = doorWidth;
            this.doorHeight = doorHeight;
            this.hingeSide = hingeSide;
            this.doorType = doorType;
            this.handleGripWidth = handleGripWidth;
            this.doorCenter = doorCenter;
            this.handlePose = handlePose;
        }

        public static DoorInfoMsg Deserialize(MessageDeserializer deserializer) => new DoorInfoMsg(deserializer);

        private DoorInfoMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.doorDetected);
            deserializer.Read(out this.doorWidth);
            deserializer.Read(out this.doorHeight);
            deserializer.Read(out this.hingeSide);
            deserializer.Read(out this.doorType);
            deserializer.Read(out this.handleGripWidth);
            this.doorCenter = Geometry.PointMsg.Deserialize(deserializer);
            this.handlePose = Geometry.PoseStampedMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.doorDetected);
            serializer.Write(this.doorWidth);
            serializer.Write(this.doorHeight);
            serializer.Write(this.hingeSide);
            serializer.Write(this.doorType);
            serializer.Write(this.handleGripWidth);
            serializer.Write(this.doorCenter);
            serializer.Write(this.handlePose);
        }

        public override string ToString()
        {
            return "DoorInfoMsg: " +
            "\nheader: " + header.ToString() +
            "\ndoorDetected: " + doorDetected.ToString() +
            "\ndoorWidth: " + doorWidth.ToString() +
            "\ndoorHeight: " + doorHeight.ToString() +
            "\nhingeSide: " + hingeSide.ToString() +
            "\ndoorType: " + doorType.ToString() +
            "\nhandleGripWidth: " + handleGripWidth.ToString() +
            "\ndoorCenter: " + doorCenter.ToString() +
            "\nhandlePose: " + handlePose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
