//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Behaviortree
{
    [Serializable]
    public class DoorOpeningModesMsg : Message
    {
        public const string k_RosMessageName = "behaviortree_msgs/DoorOpeningModes";
        public override string RosMessageName => k_RosMessageName;

        public sbyte mode;
        public const sbyte SINGLE_WALKTHROUGH = 0;
        public const sbyte SINGLE_LOOP = 1;
        public const sbyte CONTINUOUS_ONE_DIRECTION = 2;
        public const sbyte CONTINUOUS_PULL_PUSH = 3;

        public DoorOpeningModesMsg()
        {
            this.mode = 0;
        }

        public DoorOpeningModesMsg(sbyte mode)
        {
            this.mode = mode;
        }

        public static DoorOpeningModesMsg Deserialize(MessageDeserializer deserializer) => new DoorOpeningModesMsg(deserializer);

        private DoorOpeningModesMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mode);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.mode);
        }

        public override string ToString()
        {
            return "DoorOpeningModesMsg: " +
            "\nmode: " + mode.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
