//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Behaviortree
{
    [Serializable]
    public class GraspMsg : Message
    {
        public const string k_RosMessageName = "behaviortree_msgs/Grasp";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseStampedMsg target;

        public GraspMsg()
        {
            this.target = new Geometry.PoseStampedMsg();
        }

        public GraspMsg(Geometry.PoseStampedMsg target)
        {
            this.target = target;
        }

        public static GraspMsg Deserialize(MessageDeserializer deserializer) => new GraspMsg(deserializer);

        private GraspMsg(MessageDeserializer deserializer)
        {
            this.target = Geometry.PoseStampedMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.target);
        }

        public override string ToString()
        {
            return "GraspMsg: " +
            "\ntarget: " + target.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
