//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Behaviortree
{
    [Serializable]
    public class TargetMsg : Message
    {
        public const string k_RosMessageName = "behaviortree_msgs/Target";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseStampedMsg target;
        public sbyte target_mode;
        public const sbyte BASE = 1;
        public const sbyte EE = 2;
        public sbyte base_mode;
        public const sbyte BASE_PID_CONTROL = 0;
        public const sbyte BASE_LINE_INTERPOLATION = 1;
        public const sbyte BASE_LOCAL_GUIDANCE = 2;
        public sbyte ee_mode;
        public const sbyte EE_LINE_INTERPOLATION = 1;
        public const sbyte EE_BEZIER_INTERPOLATION = 2;
        public const sbyte EE_BSPLINE_INTERPOLATION = 3;
        public Geometry.PoseStampedMsg intermediate_target;
        public string desired_motion_state;
        public double max_linear_velocity;
        public double max_angular_velocity;
        public double target_threshold_position;
        public double target_threshold_orientation;

        public TargetMsg()
        {
            this.target = new Geometry.PoseStampedMsg();
            this.target_mode = 0;
            this.base_mode = 0;
            this.ee_mode = 0;
            this.intermediate_target = new Geometry.PoseStampedMsg();
            this.desired_motion_state = "";
            this.max_linear_velocity = 0.0;
            this.max_angular_velocity = 0.0;
            this.target_threshold_position = 0.0;
            this.target_threshold_orientation = 0.0;
        }

        public TargetMsg(Geometry.PoseStampedMsg target, sbyte target_mode, sbyte base_mode, sbyte ee_mode, Geometry.PoseStampedMsg intermediate_target, string desired_motion_state, double max_linear_velocity, double max_angular_velocity, double target_threshold_position, double target_threshold_orientation)
        {
            this.target = target;
            this.target_mode = target_mode;
            this.base_mode = base_mode;
            this.ee_mode = ee_mode;
            this.intermediate_target = intermediate_target;
            this.desired_motion_state = desired_motion_state;
            this.max_linear_velocity = max_linear_velocity;
            this.max_angular_velocity = max_angular_velocity;
            this.target_threshold_position = target_threshold_position;
            this.target_threshold_orientation = target_threshold_orientation;
        }

        public static TargetMsg Deserialize(MessageDeserializer deserializer) => new TargetMsg(deserializer);

        private TargetMsg(MessageDeserializer deserializer)
        {
            this.target = Geometry.PoseStampedMsg.Deserialize(deserializer);
            deserializer.Read(out this.target_mode);
            deserializer.Read(out this.base_mode);
            deserializer.Read(out this.ee_mode);
            this.intermediate_target = Geometry.PoseStampedMsg.Deserialize(deserializer);
            deserializer.Read(out this.desired_motion_state);
            deserializer.Read(out this.max_linear_velocity);
            deserializer.Read(out this.max_angular_velocity);
            deserializer.Read(out this.target_threshold_position);
            deserializer.Read(out this.target_threshold_orientation);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.target);
            serializer.Write(this.target_mode);
            serializer.Write(this.base_mode);
            serializer.Write(this.ee_mode);
            serializer.Write(this.intermediate_target);
            serializer.Write(this.desired_motion_state);
            serializer.Write(this.max_linear_velocity);
            serializer.Write(this.max_angular_velocity);
            serializer.Write(this.target_threshold_position);
            serializer.Write(this.target_threshold_orientation);
        }

        public override string ToString()
        {
            return "TargetMsg: " +
            "\ntarget: " + target.ToString() +
            "\ntarget_mode: " + target_mode.ToString() +
            "\nbase_mode: " + base_mode.ToString() +
            "\nee_mode: " + ee_mode.ToString() +
            "\nintermediate_target: " + intermediate_target.ToString() +
            "\ndesired_motion_state: " + desired_motion_state.ToString() +
            "\nmax_linear_velocity: " + max_linear_velocity.ToString() +
            "\nmax_angular_velocity: " + max_angular_velocity.ToString() +
            "\ntarget_threshold_position: " + target_threshold_position.ToString() +
            "\ntarget_threshold_orientation: " + target_threshold_orientation.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
