//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.GridMap
{
    [Serializable]
    public class GetGridMapRequest : Message
    {
        public const string k_RosMessageName = "grid_map_msgs/GetGridMap";
        public override string RosMessageName => k_RosMessageName;

        //  Frame id of the submap position request.
        public string frame_id;
        //  Requested submap position in x-direction [m].
        public double position_x;
        //  Requested submap position in y-direction [m].
        public double position_y;
        //  Requested submap length in x-direction [m].
        public double length_x;
        //  Requested submap width in y-direction [m].
        public double length_y;
        //  Requested layers. If empty, get all layers.
        public string[] layers;

        public GetGridMapRequest()
        {
            this.frame_id = "";
            this.position_x = 0.0;
            this.position_y = 0.0;
            this.length_x = 0.0;
            this.length_y = 0.0;
            this.layers = new string[0];
        }

        public GetGridMapRequest(string frame_id, double position_x, double position_y, double length_x, double length_y, string[] layers)
        {
            this.frame_id = frame_id;
            this.position_x = position_x;
            this.position_y = position_y;
            this.length_x = length_x;
            this.length_y = length_y;
            this.layers = layers;
        }

        public static GetGridMapRequest Deserialize(MessageDeserializer deserializer) => new GetGridMapRequest(deserializer);

        private GetGridMapRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.frame_id);
            deserializer.Read(out this.position_x);
            deserializer.Read(out this.position_y);
            deserializer.Read(out this.length_x);
            deserializer.Read(out this.length_y);
            deserializer.Read(out this.layers, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.frame_id);
            serializer.Write(this.position_x);
            serializer.Write(this.position_y);
            serializer.Write(this.length_x);
            serializer.Write(this.length_y);
            serializer.WriteLength(this.layers);
            serializer.Write(this.layers);
        }

        public override string ToString()
        {
            return "GetGridMapRequest: " +
            "\nframe_id: " + frame_id.ToString() +
            "\nposition_x: " + position_x.ToString() +
            "\nposition_y: " + position_y.ToString() +
            "\nlength_x: " + length_x.ToString() +
            "\nlength_y: " + length_y.ToString() +
            "\nlayers: " + System.String.Join(", ", layers.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
