//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.GridMap
{
    [Serializable]
    public class GetGridMapInfoRequest : Message
    {
        public const string k_RosMessageName = "grid_map_msgs/GetGridMapInfo";
        public override string RosMessageName => k_RosMessageName;


        public GetGridMapInfoRequest()
        {
        }
        public static GetGridMapInfoRequest Deserialize(MessageDeserializer deserializer) => new GetGridMapInfoRequest(deserializer);

        private GetGridMapInfoRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetGridMapInfoRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
