//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.GridMap
{
    [Serializable]
    public class GetGridMapResponse : Message
    {
        public const string k_RosMessageName = "grid_map_msgs/GetGridMap";
        public override string RosMessageName => k_RosMessageName;

        //  Submap
        public GridMapMsg map;

        public GetGridMapResponse()
        {
            this.map = new GridMapMsg();
        }

        public GetGridMapResponse(GridMapMsg map)
        {
            this.map = map;
        }

        public static GetGridMapResponse Deserialize(MessageDeserializer deserializer) => new GetGridMapResponse(deserializer);

        private GetGridMapResponse(MessageDeserializer deserializer)
        {
            this.map = GridMapMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.map);
        }

        public override string ToString()
        {
            return "GetGridMapResponse: " +
            "\nmap: " + map.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
