//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.GridMap
{
    [Serializable]
    public class GetGridMapInfoResponse : Message
    {
        public const string k_RosMessageName = "grid_map_msgs/GetGridMapInfo";
        public override string RosMessageName => k_RosMessageName;

        //  Grid map info
        public GridMapInfoMsg info;

        public GetGridMapInfoResponse()
        {
            this.info = new GridMapInfoMsg();
        }

        public GetGridMapInfoResponse(GridMapInfoMsg info)
        {
            this.info = info;
        }

        public static GetGridMapInfoResponse Deserialize(MessageDeserializer deserializer) => new GetGridMapInfoResponse(deserializer);

        private GetGridMapInfoResponse(MessageDeserializer deserializer)
        {
            this.info = GridMapInfoMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.info);
        }

        public override string ToString()
        {
            return "GetGridMapInfoResponse: " +
            "\ninfo: " + info.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
