//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.GridMap
{
    [Serializable]
    public class ProcessFileRequest : Message
    {
        public const string k_RosMessageName = "grid_map_msgs/ProcessFile";
        public override string RosMessageName => k_RosMessageName;

        //  Absolute file path.
        public string file_path;
        //  For ROS bags: topic name that should be processed (optional).
        public string topic_name;

        public ProcessFileRequest()
        {
            this.file_path = "";
            this.topic_name = "";
        }

        public ProcessFileRequest(string file_path, string topic_name)
        {
            this.file_path = file_path;
            this.topic_name = topic_name;
        }

        public static ProcessFileRequest Deserialize(MessageDeserializer deserializer) => new ProcessFileRequest(deserializer);

        private ProcessFileRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.file_path);
            deserializer.Read(out this.topic_name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.file_path);
            serializer.Write(this.topic_name);
        }

        public override string ToString()
        {
            return "ProcessFileRequest: " +
            "\nfile_path: " + file_path.ToString() +
            "\ntopic_name: " + topic_name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
