//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.GridMap
{
    [Serializable]
    public class ProcessFileResponse : Message
    {
        public const string k_RosMessageName = "grid_map_msgs/ProcessFile";
        public override string RosMessageName => k_RosMessageName;

        //  True if file processing was successful.
        public bool success;

        public ProcessFileResponse()
        {
            this.success = false;
        }

        public ProcessFileResponse(bool success)
        {
            this.success = success;
        }

        public static ProcessFileResponse Deserialize(MessageDeserializer deserializer) => new ProcessFileResponse(deserializer);

        private ProcessFileResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "ProcessFileResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
