//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.GridMap
{
    [Serializable]
    public class SetGridMapRequest : Message
    {
        public const string k_RosMessageName = "grid_map_msgs/SetGridMap";
        public override string RosMessageName => k_RosMessageName;

        //  map
        public GridMapMsg map;

        public SetGridMapRequest()
        {
            this.map = new GridMapMsg();
        }

        public SetGridMapRequest(GridMapMsg map)
        {
            this.map = map;
        }

        public static SetGridMapRequest Deserialize(MessageDeserializer deserializer) => new SetGridMapRequest(deserializer);

        private SetGridMapRequest(MessageDeserializer deserializer)
        {
            this.map = GridMapMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.map);
        }

        public override string ToString()
        {
            return "SetGridMapRequest: " +
            "\nmap: " + map.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
