//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.GridMap
{
    [Serializable]
    public class SetGridMapResponse : Message
    {
        public const string k_RosMessageName = "grid_map_msgs/SetGridMap";
        public override string RosMessageName => k_RosMessageName;


        public SetGridMapResponse()
        {
        }
        public static SetGridMapResponse Deserialize(MessageDeserializer deserializer) => new SetGridMapResponse(deserializer);

        private SetGridMapResponse(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "SetGridMapResponse: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
