//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.AudioCommon
{
    [Serializable]
    public class AudioDataStampedMsg : Message
    {
        public const string k_RosMessageName = "audio_common_msgs/AudioDataStamped";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public AudioDataMsg audio;

        public AudioDataStampedMsg()
        {
            this.header = new Std.HeaderMsg();
            this.audio = new AudioDataMsg();
        }

        public AudioDataStampedMsg(Std.HeaderMsg header, AudioDataMsg audio)
        {
            this.header = header;
            this.audio = audio;
        }

        public static AudioDataStampedMsg Deserialize(MessageDeserializer deserializer) => new AudioDataStampedMsg(deserializer);

        private AudioDataStampedMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            this.audio = AudioDataMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.audio);
        }

        public override string ToString()
        {
            return "AudioDataStampedMsg: " +
            "\nheader: " + header.ToString() +
            "\naudio: " + audio.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
