//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.AudioCommon
{
    [Serializable]
    public class AudioInfoMsg : Message
    {
        public const string k_RosMessageName = "audio_common_msgs/AudioInfo";
        public override string RosMessageName => k_RosMessageName;

        //  This message contains the audio meta data
        //  Number of channels
        public byte channels;
        //  Sampling rate [Hz]
        public uint sample_rate;
        //  Audio format (e.g. S16LE)
        public string sample_format;
        //  Amount of audio data per second [bits/s]
        public uint bitrate;
        //  Audio coding format (e.g. WAVE, MP3)
        public string coding_format;

        public AudioInfoMsg()
        {
            this.channels = 0;
            this.sample_rate = 0;
            this.sample_format = "";
            this.bitrate = 0;
            this.coding_format = "";
        }

        public AudioInfoMsg(byte channels, uint sample_rate, string sample_format, uint bitrate, string coding_format)
        {
            this.channels = channels;
            this.sample_rate = sample_rate;
            this.sample_format = sample_format;
            this.bitrate = bitrate;
            this.coding_format = coding_format;
        }

        public static AudioInfoMsg Deserialize(MessageDeserializer deserializer) => new AudioInfoMsg(deserializer);

        private AudioInfoMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.channels);
            deserializer.Read(out this.sample_rate);
            deserializer.Read(out this.sample_format);
            deserializer.Read(out this.bitrate);
            deserializer.Read(out this.coding_format);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.channels);
            serializer.Write(this.sample_rate);
            serializer.Write(this.sample_format);
            serializer.Write(this.bitrate);
            serializer.Write(this.coding_format);
        }

        public override string ToString()
        {
            return "AudioInfoMsg: " +
            "\nchannels: " + channels.ToString() +
            "\nsample_rate: " + sample_rate.ToString() +
            "\nsample_format: " + sample_format.ToString() +
            "\nbitrate: " + bitrate.ToString() +
            "\ncoding_format: " + coding_format.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
