//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Behaviortree
{
    [Serializable]
    public class ActivateMissionRequest : Message
    {
        public const string k_RosMessageName = "behaviortree_msgs/ActivateMission";
        public override string RosMessageName => k_RosMessageName;

        //  Request
        public ActiveMissionMsg desired_mission;
        public TargetMsg target_pose_mission;
        public DoorOpeningMsg door_opening_mission;
        public GraspMsg grasp_mission;

        public ActivateMissionRequest()
        {
            this.desired_mission = new ActiveMissionMsg();
            this.target_pose_mission = new TargetMsg();
            this.door_opening_mission = new DoorOpeningMsg();
            this.grasp_mission = new GraspMsg();
        }

        public ActivateMissionRequest(ActiveMissionMsg desired_mission, TargetMsg target_pose_mission, DoorOpeningMsg door_opening_mission, GraspMsg grasp_mission)
        {
            this.desired_mission = desired_mission;
            this.target_pose_mission = target_pose_mission;
            this.door_opening_mission = door_opening_mission;
            this.grasp_mission = grasp_mission;
        }

        public static ActivateMissionRequest Deserialize(MessageDeserializer deserializer) => new ActivateMissionRequest(deserializer);

        private ActivateMissionRequest(MessageDeserializer deserializer)
        {
            this.desired_mission = ActiveMissionMsg.Deserialize(deserializer);
            this.target_pose_mission = TargetMsg.Deserialize(deserializer);
            this.door_opening_mission = DoorOpeningMsg.Deserialize(deserializer);
            this.grasp_mission = GraspMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.desired_mission);
            serializer.Write(this.target_pose_mission);
            serializer.Write(this.door_opening_mission);
            serializer.Write(this.grasp_mission);
        }

        public override string ToString()
        {
            return "ActivateMissionRequest: " +
            "\ndesired_mission: " + desired_mission.ToString() +
            "\ntarget_pose_mission: " + target_pose_mission.ToString() +
            "\ndoor_opening_mission: " + door_opening_mission.ToString() +
            "\ngrasp_mission: " + grasp_mission.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
