//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Behaviortree
{
    [Serializable]
    public class ActivateMissionResponse : Message
    {
        public const string k_RosMessageName = "behaviortree_msgs/ActivateMission";
        public override string RosMessageName => k_RosMessageName;

        //  Result
        public bool success;

        public ActivateMissionResponse()
        {
            this.success = false;
        }

        public ActivateMissionResponse(bool success)
        {
            this.success = success;
        }

        public static ActivateMissionResponse Deserialize(MessageDeserializer deserializer) => new ActivateMissionResponse(deserializer);

        private ActivateMissionResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "ActivateMissionResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
